car_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.car_filtering_logs_create_view, name='car_filtering_logs'),
    #path('car_more_details/', views.next_page, name='next_page'),  


    path('ajax/load_models/', views.load_models, name='ajax_load_models'), # AJAX
    path('ajax/load_years/', views.load_years, name='ajax_load_years'), # AJAX
    path('ajax/load_engines/', views.load_engines, name='ajax_load_engines'), # AJAX
    # path('ajax/load_gearboxes/', views.load_gearboxes, name='ajax_load_gearboxes'), # AJAX
    #path('ajax/load_transmissions/', views.load_transmissions, name='ajax_load_transmissions'), # AJAX
    #path('ajax/load_bantypes/', views.load_bantypes, name='ajax_load_bantypes'), # AJAX
    #path('ajax/load_fueltypes/', views.load_fueltypes, name='ajax_load_fueltypes'), # AJAX

]

car_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car_app.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

car_app/models.py
# Create your models here.
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class BanType(models.Model):
    id = models.SmallAutoField(primary_key=True)
    ban_type = models.CharField(max_length=20, blank=True, null=True)


    class Meta:
        managed = False
        db_table = 'ban_type'


class BantypeFueltype(models.Model):
    marka = models.SmallIntegerField(blank=True, null=True)
    model = models.SmallIntegerField(blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)
    engine = models.IntegerField(blank=True, null=True)
    gearbox = models.SmallIntegerField(blank=True, null=True)
    transmission = models.SmallIntegerField(blank=True, null=True)
    ban_type = models.SmallIntegerField(blank=True, null=True)
    fuel_type_id = models.SmallIntegerField(blank=True, null=True)
    fuel_type = models.CharField(max_length=10, blank=True, null=True)
    objects = models.Manager()

    # def __str__(self):
    #     return self.fuel_type

    class Meta:
        managed = False
        db_table = 'bantype_fueltype'


class Car(models.Model):
    id = models.BigAutoField(primary_key=True)
    marka = models.ForeignKey('Marka', models.DO_NOTHING, db_column='marka', blank=True, null=True)
    model = models.ForeignKey('Model', models.DO_NOTHING, db_column='model', blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    currency = models.ForeignKey('Currency', models.DO_NOTHING, db_column='currency', blank=True, null=True)
    unique_id = models.IntegerField(unique=True, blank=True, null=True)
    year = models.SmallIntegerField(blank=True, null=True)
    city = models.ForeignKey('City', models.DO_NOTHING, db_column='city', blank=True, null=True)
    engine = models.CharField(max_length=5, blank=True, null=True)
    fuel_type = models.ForeignKey('FuelType', models.DO_NOTHING, db_column='fuel_type', blank=True, null=True)
    ban_type = models.ForeignKey(BanType, models.DO_NOTHING, db_column='ban_type', blank=True, null=True)
    color = models.ForeignKey('Color', models.DO_NOTHING, db_column='color', blank=True, null=True)
    used_by_km = models.IntegerField(blank=True, null=True)
    engine_power = models.SmallIntegerField(blank=True, null=True)
    transmission = models.SmallIntegerField(blank=True, null=True)
    gearbox = models.ForeignKey('Gearbox', models.DO_NOTHING, db_column='gearbox', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    url = models.CharField(max_length=100, blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)
    loan = models.SmallIntegerField(blank=True, null=True)
    barter = models.SmallIntegerField(blank=True, null=True)
    view_count = models.IntegerField(blank=True, null=True)
    new = models.SmallIntegerField(blank=True, null=True)
    is_indexed = models.SmallIntegerField(blank=True, null=True)
    is_parsed = models.SmallIntegerField(blank=True, null=True)
    request_count = models.SmallIntegerField(blank=True, null=True)
    seller = models.ForeignKey('Seller', models.DO_NOTHING, db_column='seller', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'car'


class CarModified(models.Model):
    id = models.BigIntegerField(primary_key=True)
    marka = models.SmallIntegerField(blank=True, null=True)
    model = models.SmallIntegerField(blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    currency = models.SmallIntegerField(blank=True, null=True)
    unique_id = models.IntegerField(blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)
    city = models.SmallIntegerField(blank=True, null=True)
    engine = models.IntegerField(blank=True, null=True)
    fuel_type = models.SmallIntegerField(blank=True, null=True)
    ban_type = models.SmallIntegerField(blank=True, null=True)
    color = models.SmallIntegerField(blank=True, null=True)
    used_by_km = models.IntegerField(blank=True, null=True)
    engine_power = models.SmallIntegerField(blank=True, null=True)
    transmission = models.SmallIntegerField(blank=True, null=True)
    gearbox = models.SmallIntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    url = models.CharField(max_length=100, blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)
    loan = models.SmallIntegerField(blank=True, null=True)
    barter = models.SmallIntegerField(blank=True, null=True)
    view_count = models.IntegerField(blank=True, null=True)
    new = models.SmallIntegerField(blank=True, null=True)
    is_indexed = models.SmallIntegerField(blank=True, null=True)
    is_parsed = models.SmallIntegerField(blank=True, null=True)
    request_count = models.SmallIntegerField(blank=True, null=True)
    seller = models.BigIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'car_modified'


class CascadedCar(models.Model):
    id = models.BigIntegerField(primary_key=True)
    marka = models.SmallIntegerField(blank=True, null=True)
    model = models.SmallIntegerField(blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)
    engine = models.IntegerField(blank=True, null=True)
    gearbox = models.SmallIntegerField(blank=True, null=True)
    transmission = models.SmallIntegerField(blank=True, null=True)
    ban_type = models.SmallIntegerField(blank=True, null=True)
    fuel_type = models.SmallIntegerField(blank=True, null=True)
    used_by_km = models.IntegerField(blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    currency = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'cascaded_car'


class City(models.Model):
    id = models.SmallAutoField(primary_key=True)
    city = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'city'


class Color(models.Model):
    id = models.SmallAutoField(primary_key=True)
    color = models.CharField(max_length=15, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'color'


class Currency(models.Model):
    id = models.SmallAutoField(primary_key=True)
    currency = models.CharField(max_length=5, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'currency'


class Details(models.Model):
    id = models.BigAutoField(primary_key=True)
    details = models.ForeignKey('UniqueDetails', models.DO_NOTHING, db_column='details', blank=True, null=True)
    car = models.ForeignKey(Car, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'details'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):

templates/details.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
    <link rel="stylesheet" media="screen" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="particles-js">

        <center style="position: absolute; margin-top: 0px;">
<h2>Car Form 2</h2>

<form method="post" id="car_information_detailsForm" >
    <!-- {% csrf_token %}
    {{ form.as_p }} -->
    <!-- <input name="id" value="{{car_information.id}}" /> --> 
    {% csrf_token %}
    <table>
      {% for field in form %}
          <tr>
              <td>{{ field.label}}</td>
              <td>{{ field }}</td>
          </tr>
      {% endfor %}
  </table>
    <input type="submit" value="Submit">
</form>

</center>
</div>
<script src="{% static 'js/particles.min.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
</body>
</html>

templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
    <link rel="stylesheet" media="screen" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="particles-js">

        <center style="position: absolute; margin-top: 0px;">
<h2>Car Form</h2>

<form method="post" id="car_filtering_logsForm" data-models-url="{% url 'ajax_load_models' %}" data-years-url="{% url 'ajax_load_years' %}" data-engines-url="{% url 'ajax_load_engines' %}">

    {% csrf_token %}
    <table>
      {% for field in form %}
          <tr>
              <td>{{ field.label}}</td>
              <td>{{ field }}</td>
          </tr>
      {% endfor %}
  </table>
    <input type="submit" value="Continue">
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $("#id_marka").change(function () {
        const url = $("#car_filtering_logsForm").attr("data-models-url");  // get the url of the `load_models` view
        const markaId = $(this).val();  // get the selected marka ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /ajax/load-models/ )
            data: {
                'marka_id': markaId       // add the marka id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_models` view function
                console.log(data)
                marka_id = markaId;
                $("#id_model").html(data);  // replace the contents of the model input with the data that came from the server
                
            }
        })

    });

    $("#id_model").change(function () {
      var url = $("#car_filtering_logsForm").attr("data-years-url");
      var modelId = $(this).val();
      // var markaId = marka_id;
      $.ajax({
        url: url,
        data: {
          'model_id': modelId,
          'marka_id': marka_id
        },
        success: function (data) {
          model_id = modelId;
          console.log(data)
          $("#id_year").html(data);
        }
      })
    });

    $("#id_year").change(function () {
      var url = $("#car_filtering_logsForm").attr("data-engines-url");
      var yearId = $(this).val();
      // var markaId = marka_id;
      // var modelId = model_id;
      $.ajax({
        url: url,
        data: {
          'year_id': yearId,
          'marka_id': marka_id,
          'model_id': model_id
        },
        success: function (data) {
          console.log(data)
          year_id = yearId;
          $("#id_engine").html(data);
        }
      })
    });

    // $("#id_engine").change(function () {
    //   var url = $("#car_informationForm").attr("data-gearboxes-url");
    //   var engineId = $(this).val();
    //   $.ajax({
    //     url: url,
    //     data: {
    //       'engine_id': engineId,
    //       'year_id': year_id,
    //       'marka_id': marka_id,
    //       'model_id': model_id
    //     },
    //     success: function (data) {
    //         console.log(data)
    //         engine_id = engineId;
    //       $("#id_gearbox").html(data);
    //     }
    //   })
    //   
    // });

    // $("#id_gearbox").change(function () {
    //   var url = $("#car_informationForm").attr("data-transmissions-url");
    //   var gearboxId = $(this).val();
    //   $.ajax({
    //     url: url,
    //     data: {
    //       'gearbox_id': gearboxId,
    //       'engine_id': engine_id,
    //       'year_id': year_id,
    //       'marka_id': marka_id,
    //       'model_id': model_id
    //     },
    //     success: function (data) {
          
    //         console.log(data)
    //         gearbox_id = gearboxId;
    //       $("#id_transmission").html(data);
    //     }
    //   })
    //   return gearbox_id;
    // });


    // $("#id_transmission").change(function () {
    //   var url = $("#car_informationForm").attr("data-bantypes-url");
    //   var transmissionId = $(this).val();
    //   $.ajax({
    //     url: url,
    //     data: {
    //       'transmission_id': transmissionId,
    //       'gearbox_id': gearbox_id,
    //       'engine_id': engine_id,
    //       'year_id': year_id,
    //       'marka_id': marka_id,
    //       'model_id': model_id
    //     },
    //     success: function (data) {
    //         console.log(data)
    //         transmission_id = transmissionId;
    //       $("#id_ban_type").html(data);
    //     }
    //   })
    //   return transmission_id;
    // });

    // $("#id_ban_type").change(function () {
    //   var url = $("#car_informationForm").attr("data-fueltypes-url");
    //   var bantypeId = $(this).val();
    //   $.ajax({
    //     url: url,
    //     data: {
    //       'ban_type_id': bantypeId,
    //       'transmission_id': transmission_id,
    //       'gearbox_id': gearbox_id,
    //       'engine_id': engine_id,
    //       'year_id': year_id,
    //       'marka_id': marka_id,
    //       'model_id': model_id
    //     },
    //     success: function (data) {
    //         console.log(data)
    //         ban_type_id = bantypeId;
    //       $("#id_fuel_type").html(data);
    //     }
    //   })
    //   return ban_type_id;
    // });

</script>
</center>
</div>
<script src="{% static 'js/particles.min.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
</body>
</html>